services:
  api:
    image: node:20-bullseye
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
