services:
  api:
    image: node:20-bullseye
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_TYPE=${DB_TYPE}
      - TEST_DB_HOST=${TEST_DB_HOST}
      - TEST_DB_PORT=${TEST_DB_PORT}
      - TEST_DB_USERNAME=${TEST_DB_USERNAME}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_DB_DATABASE=${TEST_DB_DATABASE}
      - TEST_DB_TYPE=${TEST_DB_TYPE}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_CALLBACK_LINK_URL=${GOOGLE_CALLBACK_LINK_URL}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
      - ./files:/files
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    networks:
      - backend
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:
